"""Update bots model 2

Revision ID: 498f93b5ed56
Revises: 5d724b14ab78
Create Date: 2025-11-29 17:49:48.956104

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy import text
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = '498f93b5ed56'
down_revision: Union[str, Sequence[str], None] = '5d724b14ab78'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bots')
    op.create_table('bots',
                    sa.Column('operators', sa.JSON(), nullable=True),
                    sa.Column('id', sa.Integer(),  server_default='{}', nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    # пришлось сделать такую миграцию, так как в sqlite какие то проблемы с изменением hullable
                    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('bots', 'id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)
    op.alter_column('bots', 'operators',
               existing_type=sqlite.JSON(),
               nullable=True)
    # ### end Alembic commands ###
