"""Update models for bots

Revision ID: 5d724b14ab78
Revises: ab1d5b2e5233
Create Date: 2025-11-29 17:34:19.302848

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = '5d724b14ab78'
down_revision: Union[str, Sequence[str], None] = 'ab1d5b2e5233'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bots')
    op.create_table('bots',
                    sa.Column('operators', sa.JSON(), nullable=True),
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.PrimaryKeyConstraint('id') #пришлось сделать такую миграцию, так как в sqlite какие то проблемы с изменением hullable
                    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('bots', 'operators',
               existing_type=sqlite.JSON(),
               nullable=False)
    # ### end Alembic commands ###
